Installation changed
scipion-em/scipion-em-emready pull request #2
Opened 2022-10-05 12:53 UTC by pconesa

Test added: scipion3 tests emready.tests.test_protocol_sharpening.TestEMReadySharpening Call done using conda activation env variable

2022-10-05 12:55 UTC, pconesa commented
Installation is working for me fine now after some tweaks.

But the test fails in my case:

numpy.core._exceptions.MemoryError: Unable to allocate 57.9 GiB for an array with shape (140608, 48, 48, 48) and data type float32

I do not have 58GB in my laptop.

2022-11-20 12:51 UTC, JiahuaHe commented on emready/tests/test_protocol_sharpening.py
> +            self.assertEqual(self.inputVol.getDim(),
The size of volume might be changed after applying EMReady

2022-11-20 12:51 UTC, JiahuaHe commented on emready/tests/test_protocol_sharpening.py
> +            self.assertEqual(self.inputVol.getSamplingRate(),
The sampling rate of volume is unified to 1.0 angstrom after applying EMReady

2022-11-20 12:58 UTC, JiahuaHe requested changes

2022-11-20 12:58 UTC, JiahuaHe commented on emready/tests/test_protocol_sharpening.py
> +            self.assertEqual(self.inputVol.getDim(),
The sampling rate of volume will be interpolated to 1.0 angstrom and therefore the size of volume might be changed after applying EMReady. These two assertions should be removed.

2022-11-20 12:58 UTC, JiahuaHe commented on emready/tests/test_protocol_sharpening.py
> +# * Authors:     David Maluenda (dmaluenda@cnb.csic.es) (2018)
Is author name correct?

2022-11-22 16:08 UTC, JiahuaHe approved these changes

2022-11-22 16:13 UTC, JiahuaHe requested changes

2022-11-22 16:13 UTC, JiahuaHe commented on emready/protocols/protocol_emready_sharpening.py
> +        if (48 < self.stride or self.stride < 10):
The lower limit of `stride` is 12

2022-11-22 16:41 UTC, JiahuaHe approved these changes

2022-11-22 18:35 UTC, JiahuaHe requested changes

2022-11-22 18:35 UTC, JiahuaHe commented on emready/protocols/protocol_emready_sharpening.py
> +        if (12 < self.stride < 48):
It seems that errors will be reported for stride between 12 and 48, which is just in contrast to its original purpose (to make sure 12 <= stride <= 48).

2022-11-22 18:41 UTC, JiahuaHe approved these changes

2023-06-11 08:24 UTC, merged